name: deeprl
channels:
  - defaults
  - conda-forge
  - nvidia/label/cuda-11.4.1
dependencies:
  - python=3.9
  - pip
  - cuda-nvcc
  - cuda-toolkit=11.4
  - cudnn=8.4.1.50
  - pip:
      - --requirement requirements.txt
